version: '2'
services:
  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - "6379:6379"
  hacker-news:
    image: hacker-news
    container_name: hacker-news
    links:
      - redis
    ports:
      - "8080:8080"
